// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/aakashgyl/goQuickOverview/grpcexample/pkg/pb/service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/aakashgyl/goQuickOverview/grpcexample/pkg/pb/service.proto

It has these top-level messages:
	HelloRequest
	HelloReply
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (m *HelloRequest) Preprocess() error {

	return nil
}

func (m *HelloReply) Preprocess() error {

	return nil
}
